CREATE DATABASE ATMSystem;

USE ATMSystem;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    pin INT NOT NULL,
    balance DOUBLE DEFAULT 0
);
